### ISSUE TITLE
Download video

### ISSUE THREAD

**Issue by josefredohd** [kamyroll/Kamyroll-Tauri#15]
How can I download the video from the m3u8 link?

**Comment by gaslec** [comment]
Easier version : open the m3u8 link in VLC and convert/save to mp4. 
Faster option : if you are used to cli you can also use ffmpeg or yt-dlp with external downloaders like aria2c or axel.

**Comment by Bilnaa** [comment]
# For Crunchyroll and Neko-Sama: 
 - Copy the link through the button
 - Paste it in your favorite software to convert and download the actual tracks (as said above VLC for the simplicity or yt-dlp if you're not scared of the terminal)
# For ADN : 
You have to be careful since the hard-subs versions on there are low quality, I provided the link for the subs in the link with the m3u8 link (after ``?subs=``), you'll have to use one of the softwares said above for downloading the video and also the download the subs separately you can use your browser for that and then use a software like HandBrake to implement the subs inside the video.

In the future, everything will be implemented inside the software to avoid this mess lol.
